[박지훈] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/31-westagram-backend-2-team pull request #10
Opened 2022-03-18 11:44 UTC by angrybirdpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
- views.py SignInView 생성 (로그인 기능)
- users/urls.py SignInView 경로 추가

## 기타 질문 및 특이 사항
- 제가 SignInView if not 부분에 길이가 길어져서 엔터로 나눴는데, 이 부분이 code convention 정책에 맞는지 헷갈립니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 07:59 UTC, KwangsooPark607 commented
LGTM

2022-03-21 08:21 UTC, mquat commented
수정사항 없습니다.

2022-03-22 01:39 UTC, kyeongraekim requested changes

2022-03-22 01:39 UTC, kyeongraekim commented on students/jeehoon/users/views.py
> +            if not User.objects.filter(
.exists() 메소드를 붙였을 때의 이점을 한 번 리서치 해보시고 적용을 검토해주세요!~

2022-03-22 01:39 UTC, kyeongraekim commented on students/jeehoon/users/views.py
> +                return JsonResponse({'Message' : "INVALID_USER"}, status=401)
리턴 메세지의 통일감을 주기위해 소문자로 변경해주셔도 나쁘지 않을 것 같네요!~

2022-03-22 02:22 UTC, angrybirdpark commented on students/jeehoon/users/views.py
> +            if not User.objects.filter(
넵 감사합니다! 존재하는 것만 확인할때는 exists로 쓰는 게 모든 db 정보를 확인하는 filter보다 효율적인 걸로 확인했습니다..!
그러나, 미리 진행하던 mission 6 jwt 과제에서 filter보다 get이 더 효율적인 것 같아 미리 get으로 수정하였습니다!

2022-03-22 02:23 UTC, angrybirdpark commented on students/jeehoon/users/views.py
> +                return JsonResponse({'Message' : "INVALID_USER"}, status=401)
넵 Invalid_User로 수정 완료했습니다!

2022-03-22 04:05 UTC, angrybirdpark commented on students/jeehoon/users/views.py
> +            if not User.objects.filter(
앗, 제가 혼동이 있었어서 다시 원래 요청해주신대로 exists로 수정해서 올려드립니다 ㅠ

2022-03-22 05:05 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 05:05 UTC, merged