[박광수] Mission 4 : 로그인 기능 구현
wecode-bootcamp-korea/31-westagram-backend-2-team pull request #11
Opened 2022-03-21 07:51 UTC by KwangsooPark607

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 기능 구현
		 
## 수정 사항들 자세한 내용
- 로그인 기능 구현
- ObjectDoesNotExist Error import 해서  미등록 유저 에러처리했습니다

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 07:59 UTC, angrybirdpark commented
이상 없어보입니다 코드가 예뻐요 :)

2022-03-21 08:16 UTC, mquat commented
저도 수정사항 없습니다.

2022-03-21 08:32 UTC, KwangsooPark607 commented
> 이상 없어보입니다 코드가 예뻐요 :)

감사합니다 :)

2022-03-21 08:33 UTC, KwangsooPark607 commented
> 저도 수정사항 없습니다.

감사합니다:)

2022-03-22 02:05 UTC, kyeongraekim requested changes

2022-03-22 02:05 UTC, kyeongraekim commented on students/kwangsoo/users/views.py
> +        except ObjectDoesNotExist:
ObjectDoesNotExist 외에 ModelDoesNotExist 예외처리문도 있습니다. 둘의 차이를 비교해보시고 더 효율적인 내용을 한 번 참고하여 골라보세요!

그리고 51번 라인의 내용을 통해서 해당 에러문이 발동될텐데 2중으로 에러핸들링 장치를 심어주신 느낌이네요~ 기획을 고심해주셔서 하나만을 남길 수 있게 변경해보세요!~

2022-03-22 03:46 UTC, KwangsooPark607 commented
`ObjectDoesNotExist` 에러를 `User.DoesNotExist' 에러로 수정하는 방법과
filter method를 통해 에러를 이중으로 잡지 않고 한 번에 해결하는 방법중에 후자를 선택했습니다.

2022-03-22 05:06 UTC, bigfanoftim requested changes

2022-03-22 05:06 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +from django.core.exceptions import ObjectDoesNotExist
수정하셨으면 불필요한 import는 지워주세요~

2022-03-22 05:15 UTC, KwangsooPark607 commented
`import ObjectDoesNotExist `
삭제하였습니다.

2022-03-22 06:04 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 06:04 UTC, merged