[류미류] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/31-westagram-backend-2-team pull request #12
Opened 2022-03-21 08:05 UTC by mquat

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- users 앱 / signin 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- views.py에 signin 클래스 추가 완료 
- urls.py에 경로 추가 완료 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 08:33 UTC, angrybirdpark commented on students/meeryu/users/views.py
> +                if users.filter(email=data['email'], password=data['password']).exists():
User.objects.all().filter 보다 따로 users 변수 설정 없이
if User.objects.filter가 더 간략해보이는데 의견 부탁드립니다!

2022-03-21 08:37 UTC, KwangsooPark607 commented on students/meeryu/users/views.py
> +                users = User.objects.all()
유저 데이터의 모든 객체를 다 불러오면 DB의 데이터량이 많아졌을 때 연산량이 많아지게 되지 않을까 하는 생각입니다.

2022-03-21 08:37 UTC, KwangsooPark607 commented on students/meeryu/users/views.py
> +                if users.filter(email=data['email'], password=data['password']).exists():
위의 `User.objects.all()` 지우고
`if User.objects.filter()`를 바로 사용하시는 건 어떨지 제안드립니다 :)

2022-03-21 08:38 UTC, mquat commented on students/meeryu/users/views.py
> +                users = User.objects.all()
수정 완료 했습니다. 감사합니다.

2022-03-21 08:38 UTC, mquat commented on students/meeryu/users/views.py
> +                if users.filter(email=data['email'], password=data['password']).exists():
수정 완료 했습니다. 감사합니다.

2022-03-22 02:07 UTC, kyeongraekim requested changes

2022-03-22 02:07 UTC, kyeongraekim commented on students/meeryu/users/views.py
> +                if User.objects.filter(email=data['email'], password=data['password']).exists():
추후 코드의 확장성 및 사용가능성에 대비하여 고려하여서 email과 password에 대한 내용은 변수선언을 미리 따로 해주시는게 좋을 것 같네요!~

2022-03-22 02:12 UTC, mquat commented
확장성을 고려해야 함을 배웠습니다, 감사합니다. 말씀하신 부분 수정했으니 확인 부탁 드립니다.

2022-03-22 05:07 UTC, bigfanoftim requested changes

2022-03-22 05:07 UTC, bigfanoftim commented on students/meeryu/users/views.py
> +                return JsonResponse({"message": "INVALID_USER"}, status = 401)
실패 케이스 예외처리를 if문으로 작성해주시고 성공은 맨 아래줄에 작성해주시면 더 좋을 것 같네요~

2022-03-22 05:19 UTC, mquat commented
말씀하신 부분 수정했습니다, 확인 부탁 드립니다 !

2022-03-22 07:03 UTC, bigfanoftim requested changes

2022-03-22 07:03 UTC, bigfanoftim commented on students/meeryu/users/views.py
> +                return JsonResponse({"message":"KEYERROR"}, status = 400)
다른 에러 메세지와 마찬가지로 통일된 양식으로 작성해주시면 더 좋을 것 같아요 미류님!
```suggestion
                return JsonResponse({"message":"KEY_ERROR"}, status = 400)
```

2022-03-22 07:08 UTC, mquat commented
수정 완료 했습니다 ~! (메지 이름 양식, 띄어쓰기 등 맞추는 것 확인함)

2022-03-22 07:15 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 07:15 UTC, merged