[박광수] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/31-westagram-backend-2-team pull request #14
Opened 2022-03-22 06:29 UTC by KwangsooPark607

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
- 회원가입 비밀번호 암호화 적용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-22 07:45 UTC, mquat commented on students/kwangsoo/users/views.py
>              User.objects.create(
create 목록 중에서, password = hashed_pw로 바꿔야 할 것 같습니당~

2022-03-22 07:47 UTC, angrybirdpark commented on students/kwangsoo/users/views.py
>              User.objects.create(
저도 미류님 피어리뷰와 동일합니다!

2022-03-22 07:51 UTC, KwangsooPark607 commented on students/kwangsoo/users/views.py
>              User.objects.create(
두 분 모두 감사합니다 !!

2022-03-22 08:16 UTC, bigfanoftim requested changes

2022-03-22 08:16 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +            hashed_pw    = hashed_pw.decode('utf-8')
- 디코딩을 미리하면 되지않을까요?ㅎㅎ 굳이 두줄로 나눠서 작성할 필요가 없어보입니다.
- 추가로 지금까지 전부다 `password`로 작성해주시다가 `pw`와 같은 줄임말을 사용하는 것은 좋지 않아보입니다. 간단한 변수라고 생각해서 줄이다보면 사람이란게 어디까지 줄여버릴지 모르기 때문에....
```suggestion
            hashed_password    = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
```

2022-03-22 08:36 UTC, KwangsooPark607 commented
감사합니다 호준님. 수정요청 주신 사항 모두 반영했습니다.

2022-03-24 07:08 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-24 07:08 UTC, merged