[박광수] Mission3 : 회원가입 기능 구현
wecode-bootcamp-korea/31-westagram-backend-2-team pull request #8
Opened 2022-03-18 06:43 UTC by KwangsooPark607

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
- 이메일 중복 체크 구현
- 이메일 형식 체크 구현
- 비밀번호 형식 체크 구현

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-18 06:53 UTC, bigfanoftim requested changes

2022-03-18 06:53 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +class UserView(View):
`UserView`라고 하게 되면 너무 광범위한 것 같습니다. 기능에 맞게 `SignUpView` 등 정확한 네이밍이 필요해 보입니다!

2022-03-18 06:53 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +            passwordchecker = re.compile("^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$")
정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, `match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.

```python
import re

REGEX_EMAIL    = '^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
REGEX_PASSWORD = '^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$'

    if not re.match(REGEX_EMAIL, value):
        return JsonResponse(...)

    if not re.match(REGEX_EMAIL, value):
        return JsonResponse(...)
```

2022-03-18 06:53 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +            if emailchecker.match(email) == None:
파이썬 PEP 8 프로그래밍 권고에는 비교문 관련해서 어떤 형식을 사용하라고 안내되어 있습니다.

- True/False를 비교할 때는 if문에 변수만 사용하도록 한다.
- 동등성(단순히 값만 비교하는 경우)을 검증할 때는 `==` 혹은 `!=` 같은 연산자를 사용하도록 한다.
- 동일성(객체의 고유 메모리 주소로 비교하는 경우)을 검증할 때는 is나 is not을 사용한다.

즉 아래의 경우는 True/False만을 비교하기 때문에 `==`는 사용할 필요가 없습니다.

```python
if not ...:
```

2022-03-18 06:53 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +                return JsonResponse({'Message' : 'Not a valid password. Password must be more than eight characters including any character, number and speical characters'}, status = 400)
에러메세지는 프론트엔드에서 처리하기 용이하게끔 명확하고 간결한 메세지를 전달해주는게 일반적입니다.
```python
return JsonResponse({'message' : 'INVALID_PASSWORD'}, ...)
```

2022-03-18 07:07 UTC, KwangsooPark607 commented
수정요청사항 모두 반영하였습니다.

- Userview 이름 변경
- 정규표현식 compile 대신 match 사용
- 에러처리 if not
- 에러메세지 간결하게 수정

2022-03-18 07:29 UTC, KwangsooPark607 commented
urls.py 에서 수정한 class 이름 반영해서 다시 push 했습니다.

2022-03-18 07:46 UTC, bigfanoftim requested changes

2022-03-18 07:46 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 201)
```suggestion
            if not re.match(REGEX_PASSWORD, password):
                return JsonResponse({'Message' : 'INVALID_PASSWORD'}, status = 400)

            User.objects.create(
                name         = name,
                email        = email,
                password     = password,
                phone_number = phone_number,
            )
            
            return JsonResponse({'message' : 'SUCCESS'}, status = 201)
```

2022-03-18 07:46 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +                return JsonResponse({'message' : 'SUCCESS'}, status = 201)
위와 같이 훨씬 더 간결하게 작성할 수 있을 것 같네요~

2022-03-18 08:04 UTC, KwangsooPark607 commented
수정사항 반영했습니다

- if, elif, else문을 if만 사용하여 간단히 만듦

2022-03-21 05:12 UTC, bigfanoftim requested changes
광수님 코드 너무 깔끔하고 좋습니다! 다만, 회원가입 시도 시 같은 이메일이 이미 존재하는 경우에 대한 예외처리가 필요해 보입니다.

2022-03-21 05:58 UTC, KwangsooPark607 commented
말씀하신대로 이메일 중복 체크 에러메세지 추가해서 올립니다!

2022-03-21 06:20 UTC, bigfanoftim requested changes

2022-03-21 06:20 UTC, bigfanoftim commented on students/kwangsoo/users/views.py
> +            if User.objects.get(email=email):
`get` 메소드를 쓰게되면 객체를 가져옵니다.
`filter`와 `exists`로만 판단하는게 더 좋아보이네요~

2022-03-21 06:52 UTC, KwangsooPark607 commented
filter 와 exist를 이용하여 이메일 중복체크 기능 수정하였습니다.

2022-03-21 07:15 UTC, KwangsooPark607 commented
이메일 중복체크 에러메세지 오타 수정했습니다.

2022-03-21 07:41 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-21 07:41 UTC, merged